HTM_Teste_Fazenda/HTM_Teste_Fazenda/Controllers/FazendaController.cs
using HTM_Teste_Fazenda.Core;
using HTM_Teste_Fazenda.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace HTM_Teste_Fazenda.Controllers
{
  public class FazendaController : Controller
  {
    // GET: Fazenda
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult NewEdit()
    {
      return View();
    }

    [HttpGet]
    public ActionResult NewEditJson(int? id)
    {
      FazendaNewEditVM fazendaVm = new FazendaNewEditVM();

      if (id.HasValue)
      {
        fazendaVm = new FazendaNewEditDb().ListarPorId(id.Value);
        fazendaVm.Talhoes = new TalhaoNewEditDb().ListarPorIdFazenda(id.Value);
      }

      return Json(fazendaVm, JsonRequestBehavior.AllowGet);
    }

    [HttpPost]
    public ActionResult List(ListVM listVM)
    {
      FazendaNewEditVM fazendaVM = new FazendaNewEditVM();
      fazendaVM.Descricao = listVM.Descricao;
      fazendaVM.Ativo = listVM.Ativo;

      List<FazendaNewEditVM> lstFazenda = new FazendaNewEditDb().ListarPorParametros(fazendaVM);

      return Json(new { Data = lstFazenda });
    }

    [HttpPost]
    public ActionResult NewEdit(FazendaNewEditVM fazendaVm)
    {
      bool sucesso = true;
      FazendaNewEditDb fazendaDb = new FazendaNewEditDb();
      TalhaoNewEditDb talhaoDb = new TalhaoNewEditDb();

      if (string.IsNullOrEmpty(fazendaVm.Descricao))
      {
        fazendaVm.Sucesso = false;
        fazendaVm.Mensagem = "Preencha o campo descrição.";
        return Json(new { Data = fazendaVm });
      }

      FazendaNewEditVM fazendaVMValidar = fazendaDb.ListarPorDescricao(fazendaVm.Descricao.TrimStart().TrimEnd());
      if (fazendaVMValidar != null && fazendaVMValidar.Id != fazendaVm.Id)
      {
        fazendaVm.Sucesso = false;
        fazendaVm.Mensagem = "Já existe uma fazenda com esta descrição.";
      }
      else
      {
        using (TransactionScope transacao = new TransactionScope())
        {
          sucesso = fazendaDb.Salvar(fazendaVm, string.Empty);
          if (sucesso)
          {
            if (fazendaVm.Talhoes != null)
            {
              foreach (var item in fazendaVm.Talhoes)
              {
                if (item != null)
                {
                  item.IdFazenda = fazendaVm.Id;

                  sucesso = talhaoDb.Salvar(item, string.Empty);
                  if (!sucesso)
                  {
                    fazendaVm.Sucesso = sucesso;
                    fazendaVm.Mensagem = "Erro ao salvar o Talhão.";
                    break;
                  }
                }
              }
            }

            List<TalhaoNewEditVM> lstTalhoes = new TalhaoNewEditDb().ListarPorIdFazenda(fazendaVm.Id);

            foreach (var item in lstTalhoes)
            {
              if (fazendaVm.Talhoes == null || !fazendaVm.Talhoes.ToList().Exists(p => p.Id == item.Id))
              {
                sucesso = talhaoDb.Excluir(item, string.Empty);
                if (!sucesso)
                {
                  fazendaVm.Sucesso = sucesso;
                  fazendaVm.Mensagem = "Erro ao excluir o Talhão.";
                  return Json(new { Data = fazendaVm });
                }
              }
            }
            if (sucesso)
            {
              fazendaVm.Sucesso = sucesso;
              transacao.Complete();
            }
          }
          else
          {
            fazendaVm.Sucesso = sucesso;
            fazendaVm.Mensagem = "Erro ao salvar a Fazenda.";
            return Json(new { Data = fazendaVm });
          }
        }
      }

      return Json(new { Data = fazendaVm });
    }
  }
}

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HTM_Teste_Fazenda.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Fazenda/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section Scripts{

    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>
    <script src="~/Scripts/Fazenda/Index.js"></script>

}

<form id="frmListFazenda" name="frmListFazenda">
    <h3>Listagem de Fazendas</h3>

    <div class="row">
        <div class="col-md-12">
            <legend style="padding-top:20px;">Filtro</legend>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <label>Descrição</label>
            <input class="form-control" type="text" id="txtDescricao" name="txtDescricao" data-bind="value:Descricao" />
        </div>
        <div class="col-md-3">
            <label>Ativo</label>
            <select class="form-control" id="ddlAtivo" name="ddlAtivo" data-bind="value: Ativo">
                <option value="">Todos</option>
                <option value="true">Ativo</option>
                <option value="false">Inativo</option>
            </select>
        </div>
        <div class="col-md-3" style="padding-top:25px;">
            <button id="btnPesquisar" name="btnPesquisar" data-bind="click:Pesquisar" class="btn btn-default">Pesquisar</button>
        </div>
    </div>

    <div class="row" style="padding-top: 10px;">
        <div class="col-md-3">
            <div class="form-group">
                <a href="NewEdit" class="btn btn-info">Novo</a>
            </div>
        </div>
    </div>
    <div class="row" style="padding-top: 10px;">
        <div class="col-md-12">
            <table width="100%;">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Detalhes</th>
                        <th>Talhões</th>
                        <th>Ativo</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: vm.Data">
                    <tr>
                        <td data-bind="text: Descricao()"></td>
                        <td data-bind="text: Detalhes()"></td>
                        <td data-bind="text: QtdeTalhoes()"></td>
                        <td data-bind="text: AtivoView()"></td>
                        <td><a data-bind="attr: { href: 'NewEdit/' + Id() }">Editar</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</form>

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Fazenda/NewEdit.cshtml
@{
    ViewBag.Title = "NewEdit";
}

@section Scripts{

    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>
    <script src="~/Scripts/Fazenda/NewEdit.js"></script>

}

<form id="frmFazenda" name="frmFazenda">
    <h3>Edição de Fazendas</h3>

    <div class="row">
        <div class="col-md-12">
            <legend style="padding-top:20px;">Dados Básicos</legend>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <button id="btnCancelar" name="btnCancelar" class="btn btn-danger" data-bind="click:Cancelar">Voltar / Cancelar</button>
        </div>
        <div class="col-md-1">
            <button id="btnSalvar" name="btnSalvar" class="btn btn-success" data-bind="click:Salvar">Salvar</button>
        </div>
    </div>
    <br />

    <div class="row">
        <div class="col-md-3">
            <label>Id</label>
            <input class="form-control" type="text" id="txtId" name="txtId" data-bind="value:Id, attr: { disabled: true }" />
        </div>
        <div class="col-md-3">
            <label>Nome</label>
            <input class="form-control" type="text" id="txtDescricao" required name="txtDescricao" data-bind="value:Descricao" />
        </div>
        <div class="col-md-3">
            <label>Sigla</label>
            <input class="form-control" type="text" id="txtSigla" name="txtSigla" data-bind="value:Sigla" />
        </div>
    </div>

    <div class="row" style="padding-top:10px;">
        <div class="col-md-3">
            <label>Proprietário</label>
            <select class="form-control" id="ddlProprietario" name="ddlProprietario" data-bind="value:IdProprietario">
                <option value="0">Selecione</option>
                <option value="1">Humberto Meirelles</option>
                <option value="2">Everton França</option>
                <option value="3">André Oliveira</option>
            </select>
        </div>
        <div class="col-md-3">
            <label>Município</label>
            <select class="form-control" id="ddlMunicipio" name="ddlMunicipio" data-bind="value:IdMunicipio">
                <option value="0">Selecione</option>
                <option value="1">Ribeirão Preto (SP)</option>
                <option value="2">Batatais (SP)</option>
                <option value="3">Cravinhos (SP)</option>
            </select>
        </div>
        <div class="col-md-3" style="padding-top:25px;">
            <label>Ativo</label>
            <input type="checkbox" id="chkAtivo" name="chkAtivo" data-bind="checked:Ativo" />
        </div>

    </div>


    <div class="row" style="padding-top:20px;">
        <div class="col-md-12">
            <legend>Talhões</legend>
            <button type="button" id="btnNovoTalhao" name="btnNovoTalhao" class="btn btn-info" data-toggle="modal" data-target="#frmModal" data-bind="click: koTalhao.New">
                Novo
            </button>
        </div>
    </div>

    <div class="row" style="padding-top: 10px;">
        <div class="col-md-12">
            <table width="100%;">
                <thead>
                    <tr>
                        <th>Descrição</th>
                        <th>Ativo</th>
                        <th colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: vm.Talhoes">
                    <tr>
                        <td data-bind="text: Descricao"></td>
                        <td data-bind="text: Ativo"></td>
                        <td><a href="#" data-bind="click: function (data, elem) { koTalhao.Edit($index()); }">Editar</a></td>
                        <td><a href="#" data-bind="click: function (data, elem) { koTalhao.Remove($index()); }">Remover</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</form>

<!-- Modal -->
<div class="modal fade" id="frmModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form id="_formModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Cadastro de Talhões da Fazenda</h4>
                </div>
                <div class="modal-body" data-bind="with: Talhao">

                    <div class="row">
                        <div class="col-md-3">
                            <label>Id</label>
                            <input class="form-control" type="text" id="txtTalhaoId" name="txtTalhaoId" data-bind="value:Id, attr: { disabled: true }" />
                        </div>
                        <div class="col-md-6">
                            <label>Descrição</label>
                            <input class="form-control" type="text" id="txtTalhaoDescricao" name="txtDescricao" data-bind="value:Descricao" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3" style="padding-top:25px;">
                            <label>Ativo</label>
                            <input type="checkbox" id="chkAtivo" name="chkTalhaoAtivo" data-bind="checked:Ativo" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bind="click: koTalhao.Save">Salvar</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Voltar / Cancelar</button>
                </div>
            </div>
        </div>
    </form>
</div>

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HTM_Teste_Fazenda/HTM_Teste_Fazenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Cadastro de Fazendas / Talhões", "Index", "Fazenda", new { area = "" }, new { @class = "navbar-brand" })*@
                <a class="navbar-brand" href="/Fazenda/Index">Cadastro de Fazendas / Talhões</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>